/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calcu.h"

bool_t
xdr_entrada (XDR *xdrs, entrada *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion (XDR *xdrs, operacion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_entrada (xdrs, &objp->op))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->simbolo, 3,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->resultado))
		 return FALSE;
	return TRUE;
}
