/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCU_H_RPCGEN
#define _CALCU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entrada {
	float arg1;
	float arg2;
};
typedef struct entrada entrada;

struct operacion {
	entrada op;
	char simbolo[3];
	float resultado;
};
typedef struct operacion operacion;

#define CALCULADORA 0x30000001
#define CALCULADORA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  float * suma_1(entrada *, CLIENT *);
extern  float * suma_1_svc(entrada *, struct svc_req *);
#define RESTA 2
extern  float * resta_1(entrada *, CLIENT *);
extern  float * resta_1_svc(entrada *, struct svc_req *);
#define MULTIPLICACION 3
extern  float * multiplicacion_1(entrada *, CLIENT *);
extern  float * multiplicacion_1_svc(entrada *, struct svc_req *);
#define DIVISION 4
extern  float * division_1(entrada *, CLIENT *);
extern  float * division_1_svc(entrada *, struct svc_req *);
#define POTENCIA 5
extern  float * potencia_1(entrada *, CLIENT *);
extern  float * potencia_1_svc(entrada *, struct svc_req *);
#define PROMEDIO 6
extern  float * promedio_1(entrada *, CLIENT *);
extern  float * promedio_1_svc(entrada *, struct svc_req *);
#define raiz 7
extern  float * raiz_1(entrada *, CLIENT *);
extern  float * raiz_1_svc(entrada *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define RESTA 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define MULTIPLICACION 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
#define POTENCIA 5
extern  float * potencia_1();
extern  float * potencia_1_svc();
#define PROMEDIO 6
extern  float * promedio_1();
extern  float * promedio_1_svc();
#define raiz 7
extern  float * raiz_1();
extern  float * raiz_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entrada (XDR *, entrada*);
extern  bool_t xdr_operacion (XDR *, operacion*);

#else /* K&R C */
extern bool_t xdr_entrada ();
extern bool_t xdr_operacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCU_H_RPCGEN */
