/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"


void
calculadora_1(char *host, int op)
{
	CLIENT *clnt;
	float  *result_1;
	entrada  suma_1_arg;
	float  *result_2;
	entrada  resta_1_arg;
	float  *result_3;
	entrada  multiplicacion_1_arg;
	float  *result_4;
	entrada  division_1_arg;
	float  *result_5;
	entrada  potencia_1_arg;
	float  *result_6;
	entrada  promedio_1_arg;
	float  *result_7;
	entrada  raiz_1_arg;
	

		
		
	#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	
	
	
	
	
	
	



//-------------------------------------------------

		if(op==1){
			printf("----Introdusca los elementos -----\n");
			printf("a:\n");
			scanf("%f",&suma_1_arg.arg1);
			printf("b:");
			scanf("%f",&suma_1_arg.arg2);
			printf("----------------------------------\n");
				result_1 = suma_1(&suma_1_arg, clnt);
				if (result_1 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
				}

			printf("------------------\n");
			printf("Resultado de la suma = (%.2f +%.2f) = %.2f \n\n",suma_1_arg.arg1 , suma_1_arg.arg2, *result_1 );
			printf("------------------\n");

		}
		else if(op==2){
			printf("----Introdusca los elementos -----\n");
			printf("a:\n");
			scanf("%f",&resta_1_arg.arg1);
			printf("b:");
			scanf("%f",&resta_1_arg.arg2);
			printf("----------------------------------\n");
			result_2 = resta_1(&resta_1_arg, clnt);
			if (result_2 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}


			printf("------------------\n");
			printf("Resultado de la Resta = (%.2f - %.2f) = %.2f \n\n",resta_1_arg.arg1 , resta_1_arg.arg2, *result_2 );
			printf("------------------\n");

			}
			else if(op==3){
					printf("----Introdusca los elementos -----\n");
					printf("a:\n");
					scanf("%f",&multiplicacion_1_arg.arg1);
					printf("b:");
					scanf("%f",&multiplicacion_1_arg.arg2);
					printf("----------------------------------\n");

						result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
						if (result_3 == (float *) NULL) {
							clnt_perror (clnt, "call failed");
						}

				printf("------------------\n");
				printf("Resultado de la Multiplicacion = (%.2f * %.2f) = %.2f \n\n", multiplicacion_1_arg.arg1 , multiplicacion_1_arg.arg2, *result_3 );
				printf("------------------\n");
			}
			else if(op==4){

				printf("----Introdusca los elementos -----\n");
				printf("a:\n");
				scanf("%f",&division_1_arg.arg1);
				printf("b:");
				scanf("%f",&division_1_arg.arg2);
				printf("----------------------------------\n");

						result_4 = division_1(&division_1_arg, clnt);
						if (result_4 == (float *) NULL) {
							clnt_perror (clnt, "call failed");
						}

				printf("------------------\n");
				printf("Resultado de la Division = (%.2f / %.2f) = %.2f \n\n",division_1_arg.arg1 , division_1_arg.arg2, *result_4 );
				printf("------------------\n");
			}
			else if(op==5){

					printf("----Introdusca los elementos -----\n");
					printf("base a:\n");
					scanf("%f",&potencia_1_arg.arg1);
					printf("exponente b:");
					scanf("%f",&potencia_1_arg.arg2);
					printf("----------------------------------\n");

					result_5 = potencia_1(&potencia_1_arg, clnt);
					if (result_5 == (float *) NULL) {
						clnt_perror (clnt, "call failed");
					}

				printf("------------------\n");
				printf("Resultado de la Potencia = (%.2f ^ %.2f) = %.2f \n\n",potencia_1_arg.arg1 , potencia_1_arg.arg2, *result_5 );
				printf("------------------\n");
			}
			else if(op==6){
				printf("----Introdusca los elementos -----\n");
				printf("a:\n");
				scanf("%f",&promedio_1_arg.arg1);
				printf("b:");
				scanf("%f",&promedio_1_arg.arg2);
				printf("----------------------------------\n");

				result_6 = promedio_1(&promedio_1_arg, clnt);
				if (result_6 == (float *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				printf("------------------\n");
				printf("Resultado del Promedio = (%.2f y %.2f) = %.2f \n\n",promedio_1_arg.arg1 , promedio_1_arg.arg2, *result_6 );
				printf("------------------\n");
			}
			else if(op==7){
				printf("----Introdusca un numero -----\n");
				printf("a:\n");
				scanf("%f",&raiz_1_arg.arg1);
				printf("----------------------------------\n");

					result_7 = raiz_1(&raiz_1_arg, clnt);
					if (result_7 == (float *) NULL) {
					clnt_perror (clnt, "call failed");
					}

				printf("------------------\n");
				printf("Resultado de la raiz de (%.2f) = %.2f \n\n",raiz_1_arg.arg1 , *result_7 );
				printf("------------------\n");
			}









#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */




}

		



int
main (int argc, char *argv[])
{
	char *host;
	int op=0;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

		printf("-------------------------------------------------\n");
		printf("---------------   CALCULADORA   -----------------\n");
		printf("-------------------------------------------------\n");
		printf("Ingrese una opcion:\n");
		printf("opcion 1: sumar\n");
		printf("opcion 2: restar\n");
		printf("opcion 3: multiplicar\n");
		printf("opcion 4: dividir\n");
		printf("opcion 5: potencia\n");
		printf("opcion 6: promedio\n");
		printf("opcion 7: raiz\n");
		printf("---------\n");
		scanf("%d",&op);

		host = argv[1];
		calculadora_1 (host,op);

exit (0);
}
