/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"
#include <math.h>
 #include <stdio.h>


float *
suma_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */


	 operacion oper;
	 //oper.resultado = argp->arg1 + argp->arg2;
	 //result = oper.resultado;
	  result = argp->arg1 + argp->arg2;
	  printf("------------------\n");
	printf("El Cliente a solicitado suma = (%.2f +%.2f) = %.2f \n\n",argp->arg1 , argp->arg2, result );
	printf("------------------\n\n");
	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;
	return &result;
}

float *
resta_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	  operacion oper;
	 oper.resultado = argp->arg1 - argp->arg2;
	 result = oper.resultado;

	 		printf("------------------\n");
			printf("El Cliente a Solicitado una Resta = (%.2f - %.2f) = %.2f \n\n",argp->arg1 , argp->arg2, result );
			printf("------------------\n\n");

	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;
	return &result;

	
}

float *
multiplicacion_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	  operacion oper;
	 oper.resultado = argp->arg1 * argp->arg2;
	 result = oper.resultado;

	 			printf("------------------\n");
				printf("El Cliente a Solicitado una Multiplicacion = (%.2f * %.2f) = %.2f \n\n", argp->arg1 , argp->arg2, result);
				printf("------------------\n\n");

	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;
	return &result;

	
}

float *
division_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	  operacion oper;
	 oper.resultado = argp->arg1 / argp->arg2;
	 result = oper.resultado;

	 			printf("------------------\n");
				printf("El Cliente a Solicitado una Division = (%.2f / %.2f) = %.2f \n\n",argp->arg1 , argp->arg2, result );
				printf("------------------\n\n");

	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;
	return &result;

	
}

float *
potencia_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;
	int i=1,a=0,b=0,res=0;


	/*
	 * insert server code here
	 */
	  operacion oper;
	  oper.resultado=1;

	 while(i<=argp->arg2){
        oper.resultado = oper.resultado *  argp->arg1;
        i++;
    }

    result = oper.resultado;

    			printf("------------------\n");
				printf("El Cliente a Solicitado una Potencia = (%.2f ^ %.2f) = %.2f \n\n",argp->arg1 , argp->arg2, result);
				printf("------------------\n\n");

	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;
	

	return &result;
}

float *
promedio_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	  operacion oper;
	 oper.resultado = (argp->arg1 + argp->arg2)/2;
	 result = oper.resultado;

	 			printf("------------------\n");
				printf("El Cliente a Solicitado un Promedio = (%.2f y %.2f) = %.2f \n\n",argp->arg1 , argp->arg2, result );
				printf("------------------\n\n");

	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;
	return &result;

	
}

float *
raiz_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	  operacion oper;
	 oper.resultado = sqrt(argp->arg1);
	 result = oper.resultado;

	 oper.op.arg1 = argp->arg1;

	 printf("------------------\n");
	 printf("El Cliente a Solicitado un raiz de (%.2f) = %.2f \n\n", argp->arg1 , result );
	 printf("------------------\n");
	 
	 oper.resultado = result;
	return &result;

	
}